/**
 * @file sphere.h
 * @brief Class defnition for Sphere.
 *
 * @author Andrew Fox (arfox)
 */

#ifndef _SPHERE_H_
#define _SPHERE_H_

#include "scene.h"
#include "trianglesoup.h"

/** @brief Generates geometry for a sphere.
 *  Sphere is generated by subdividing a platonic solid a number of times.
 *  @param num_of_divisions Number of times to subdivide the initial solid.
 *  @return Container holding the geometry buffers.
 */
TriangleSoup gen_sphere(int num_of_divisions);

#endif
